### ISSUE TITLE
Number 256 is blank

### ISSUE THREAD

**Issue by hugovk** [lauripiispanen/most-active-github-users-counter#1]
![smartselectimage_2017-12-03-10-55-22](https://user-images.githubusercontent.com/1324225/33523813-92dac034-d818-11e7-8ed3-d0e8945c584e.png)

http://commits.top/finland.html

It's like that on every page I checked.

**Comment by lauripiispanen** [comment]
Thanks for the heads up - this is quite interesting, as it only seems to affect the binary version on Linux. Will investigate further and fix.
