### ISSUE TITLE
Users from cities that bear the same name as certain urban cities but are from different countries appear on the list

### ISSUE THREAD

**Issue by AlwaysLivid** [lauripiispanen/most-active-github-users-counter#100]
**NOTE:** I couldn't figure out how to make a descriptive, shorter title, feel free to edit. Additionally, I haven't had the time to look into the code itself in order to check as to whether there are any existing implementations that are meant to alleviate the problem, but either way, it still exists.

**Steps to reproduce:**

- Set your location as `Athens, GA` (which stands for Georgia, in the United States.
- Alternatively, you could use `Paris, OH`, `Lisbon, OH`, `Athens, OH` or even `Moscow, OH`.

In all cases, the cities that are located in the United States bear the same names as the large, non-rural cities, which are used as alternatives to spotting a person's country, should they not mention it.

- Congrats, you've made it to a list that you're not supposed to be on!

**Potential solutions:**

- Add a "blacklist" for any occurrences of state acronyms that match a specific format (e.g. `, OH`, `, BC`) and are prioritized first.
- Add exception cases/manual overrides for specific strings.
- ???

**Examples:**

- The person that ranks first under [the Greek commits.top list](https://commits.top/greece.html) is `dzackgarza`. While the amount of commits seems fairly impressive (approximating at 36k contributions over the past year), he's currently based in Georgia, as clearly illustrated by the location he has set on his GitHub profile.

Other examples like these can be spotted throughout the list-- and quite possibly other lists as well.

**Comment by lauripiispanen** [comment]
Phew! Thanks, it's a bit tricky to spot these, but if you come across any more of them, I've now added an exclusion list for locations that can be filtered. Luckily there doesn't seem to be much users in the Ohio rural capital namesakes, but Athens and Alexandria sure are popular in the states too. :)
