### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by GrbavaCigla** [lauripiispanen/most-active-github-users-counter#103]
I was 70. in Serbia and now my contributions went -200 and now I am 171. :(

**Comment by lauripiispanen** [comment]
Are the contribution amounts still correct? Or what is the issue here?

**Comment by GrbavaCigla** [comment]
Sorry for not responding, amount of contributions aren't correct. On my profile I have 193 contributions in last year, while on website I have 161.
