### ISSUE TITLE
Private commits not counted anymore?

### ISSUE THREAD

**Issue by albinekb** [lauripiispanen/most-active-github-users-counter#106]
Hi! Very cool site, I love it, it keeps me focused 😄 However, the last update made the private and public lists the same, it seems like the private list is no longer counting private commits? 

https://commits.top/sweden_private.html
https://commits.top/sweden.html

Thanks for making this 🥳 🎈

**Comment by lauripiispanen** [comment]
Hiya! Yeah I made some changes as the GitHub API now returns even more information. So, in the most recent update the data format changed to match the new changes, but the necessary layout changes that took advantage of the new data weren't pushed until lauripiispanen/github-top@136e63c went live. So now there is an option to show only 1) commits, 2) all public contributions and 3) public + private contributions. #1 is the default. :+1:
