### ISSUE TITLE
A friend disappeared from list

### ISSUE THREAD

**Issue by Jakousa** [lauripiispanen/most-active-github-users-counter#107]
Since a recent update my friend https://github.com/sendouc (30+ followers) disappeared from the Finnish https://commits.top/finland.html list (min 20 followers). The contribution counts should be enough for him to be in all of the 3 lists.

**Comment by lauripiispanen** [comment]
Hi! Checked now with the latest data update, and so far so good. This may be a flake in the GitHub API - or rather something that was amiss with the version changes last week. Let me know if it happens again! :+1:
