### ISSUE TITLE
Add top committers in countries category

### ISSUE THREAD

**Issue by donno2048** [lauripiispanen/most-active-github-users-counter#109]
Every country has its own listing and there is a listing for worldwide but there probably should be a listing of the tops in every country

**Comment by ashkulz** [comment]
@donno2048 isn't this already implemented?

**Comment by donno2048** [comment]
@ashkulz  Not as its own list

**Comment by ashkulz** [comment]
If you look at the source, the YML output [populates `users` as per the commit count](https://github.com/lauripiispanen/most-active-github-users-counter/blob/54d46dfe291d5f61278ec1291515c45881533490/output/output.go#L95). This is then used in the website to [populate the "Commits" tab](https://github.com/lauripiispanen/github-top/blob/020c6e67c88918260df2edaf3e587330fccc29db/_layouts/default.html#L118). Not sure if you meant something else?

**Comment by donno2048** [comment]
I meant a "leaderboard" where you can see the top commiter from every country

**Comment by ashkulz** [comment]
Oh, you meant something like the home page but with a Top N users as columns, with each country/region as a row? e.g. `COUNTRY | RANK #1 | RANK #2 | RANK #3 | RANK #4 | RANK #5` for N=5. Makes sense but I'm not sure how useful it is.

**Comment by ashkulz** [comment]
@donno2048 there's one more aspect: should we have separate leaderboards as per the categories (commits, public contributions and public/private contributions)? This would mean that they would potentially need to be on different URLs.

Also, do you think we should have 5 people per country/region? Looking at the layout, I think top 3 should be okay. Or do you have a different way of formatting this?

**Comment by donno2048** [comment]
> @donno2048 there's one more aspect: should we have separate leaderboards as per the categories (commits, public contributions and public/private contributions)? This would mean that they would potentially need to be on different URLs.

Makes sense

> Also, do you think we should have 5 people per country/region? Looking at the layout, I think top 3 should be okay. Or do you have a different way of formatting this?

Top three sounds reasonable

**Comment by peymanmajidi** [comment]
I think you should sort() first, then take(1000) 
you know :)))))))))
![image](https://user-images.githubusercontent.com/24313930/147555922-8cd027f6-ed4a-48d8-a89b-c71571f96e00.png)

**Comment by ashkulz** [comment]
Ah, that's just psuedo code I think @peymanmajidi :grin:

**Comment by peymanmajidi** [comment]
you mean it works this way?

**Comment by ashkulz** [comment]
Nope, [see the actual GraphQL query that is run](https://github.com/lauripiispanen/most-active-github-users-counter/blob/54d46dfe291d5f61278ec1291515c45881533490/github/github.go#L89).

**Comment by ashkulz** [comment]
@donno2048 you're welcome to create a PR [on the `website` branch of my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain) -- I promise to review and merge it ASAP :grin:
