### ISSUE TITLE
Indian Page very unfair due to followers

### ISSUE THREAD

**Issue by IamManchanda** [lauripiispanen/most-active-github-users-counter#114]
In Most countries followers count requirement is in b/w 0-10 but in India (due to population) it's 109

1. I have 104 followers
2. I think my Commits Count come in top 10 https://github.com/IamManchanda <==> https://commits.top/india.html
3. I am not even in the list :(

**Comment by aravindvnair99** [comment]
> In Most countries followers count requirement is in b/w 0-10 but in India (due to population) it's 109
> 
> 1. I have 104 followers
> 2. I think my Commits Count come in top 10 https://github.com/IamManchanda <==> https://commits.top/india.html
> 3. I am not even in the list :(

@IamManchanda Please check carefully. You are there on the list.

List of `commits`:

![image](https://user-images.githubusercontent.com/22199259/112733443-1c599080-8f66-11eb-9841-dbfa587547d6.png)

List of `contributors`:

![image](https://user-images.githubusercontent.com/22199259/112733454-2aa7ac80-8f66-11eb-94a1-07efcf077d09.png)

List of `all`:

![image](https://user-images.githubusercontent.com/22199259/112733464-401cd680-8f66-11eb-9ceb-9c8fc418e252.png)

Last updated on:

![image](https://user-images.githubusercontent.com/22199259/112733482-51fe7980-8f66-11eb-9c94-50ccb94c9c4e.png)

Your profile as of now:

![image](https://user-images.githubusercontent.com/22199259/112733496-62aeef80-8f66-11eb-9235-afbe37256af4.png)

The stats are right, and you are on the list. Please close this invalid issue.

**Comment by IamManchanda** [comment]
Closed
