### ISSUE TITLE
I think this system Not working Real-time.  

### ISSUE THREAD

**Issue by Katheesh** [lauripiispanen/most-active-github-users-counter#121]
I have done more than thousand contributions in last month but still not updated yet. 

நான் கடந்த மாதத்தில் ஆயிரத்துக்கும் மேற்பட்ட பங்களிப்புகளைச் செய்துள்ளேன், ஆனால் இன்னும் புதுப்பிக்கப்படவில்லை.

**Comment by aravindvnair99** [comment]
> I have done more than thousand contributions in last month but still not updated yet.
> 
> நான் கடந்த மாதத்தில் ஆயிரத்துக்கும் மேற்பட்ட பங்களிப்புகளைச் செய்துள்ளேன், ஆனால் இன்னும் புதுப்பிக்கப்படவில்லை.

@Katheesh It's not real-time. The page clearly says when it is last updated. For example as you are from Sri Lank, visiting https://commits.top/sri_lanka.html right now says:

![image](https://user-images.githubusercontent.com/22199259/112733282-fe3f6080-8f64-11eb-82a1-80bf29c7fe57.png)

And under list of `commits`:

![image](https://user-images.githubusercontent.com/22199259/112733291-144d2100-8f65-11eb-9834-04aa5efd05de.png)

Under list of `contributions`:

![image](https://user-images.githubusercontent.com/22199259/112733303-347ce000-8f65-11eb-8247-1730da6ba72a.png)

Under list of `all`:

![image](https://user-images.githubusercontent.com/22199259/112733316-49f20a00-8f65-11eb-90ed-c5c269b27e1a.png)

And your GitHub contribution graph shows:

![image](https://user-images.githubusercontent.com/22199259/112733329-67bf6f00-8f65-11eb-9687-6cb63c894f7f.png)

It is clearly working as intended. Please close this invalid issue.

**Comment by Katheesh** [comment]
Thank you for your clarification @aravindvnair99 .
