### ISSUE TITLE
Build should run every 24 hours

### ISSUE THREAD

**Issue by abhinavsri360** [lauripiispanen/most-active-github-users-counter#123]
There is a feature in GitHub actions that can let the action run after the specified schedule.
In my opinion, The list should be updated every 24 hours, and in order to do that, the build should run after every 24 hours.

**Documentation link:**
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

**Comment by lauripiispanen** [comment]
Thanks, but updating the content is not triggered thru GitHub Actions. It's a separate process and would thus require a significant refactoring.

**Comment by abhinavsri360** [comment]
Ohh okay, it will be great if the process can be migrated to GitHub actions.
Thanks for responding!
