### ISSUE TITLE
All Egypt lists are empty

### ISSUE THREAD

**Issue by Abanoub-Asaad** [lauripiispanen/most-active-github-users-counter#129]
Link : https://commits.top/egypt.html 

![Screenshot from 2021-05-11 18-28-55](https://user-images.githubusercontent.com/48657780/117851734-e444ad80-b286-11eb-89a3-d004d36061f6.png)

**Comment by aryashah2k** [comment]
Hey @Abanoub-Asaad  , The issue has been resolved, all lists working fine now! You may close this issue

**Comment by Abanoub-Asaad** [comment]
Thank you so much.
