### ISSUE TITLE
More Than 15 Countries Have Lists Empty | [FIX NEEDED] 

### ISSUE THREAD

**Issue by aryashah2k** [lauripiispanen/most-active-github-users-counter#131]
The list of more than 15 countries have been affected wherein no data is being recorded and the list is rendered empty.
Few countries suffering from this issue are as follows:

|No.|Country|No.|Country|
|----|---------|----|--------|
|1.|`Australia`|6.|`Greece`|
|2.|`Brazil`|7.|`India`|
|3.|`CA, USA`|8.|`Indonesia`|
|4.|`Canada`|9.|`Iran`|
|5.|`Egypt`|10.|`Israel`|

To name a few....

Similar Issues which can be referred and closed on Fix: #122 #128 #129 #130

**Comment by BonfaceKilz** [comment]
Kenya too makes the list...

**Comment by aravindvnair99** [comment]
The fix is here: https://github.com/lauripiispanen/github-top/pull/206

**Comment by aryashah2k** [comment]
Thanks for the update @aravindvnair99 . Shall close this issue and urge others close issues related to this namely:
#122
#128
#129
#130
