### ISSUE TITLE
I can't Search by name or username.!

### ISSUE THREAD

**Issue by mariovarela99** [lauripiispanen/most-active-github-users-counter#136]
It could be cool if we can search, and find names fastly.!

**Comment by ashkulz** [comment]
Should be fixed by #115 and partially addressed via lauripiispanen/github-top#221

**Comment by ashkulz** [comment]
@mariovarela99 [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain) has this implemented via badges (_plus the above PR was merged in it_)

**Comment by trupakufi** [comment]
@ashkulz Alright, I am gonna see it now.
