### ISSUE TITLE
Does organizations table ever update?

### ISSUE THREAD

**Issue by belauzas** [lauripiispanen/most-active-github-users-counter#137]
It seems like, it's not 😬🤔

And secondary question would be: Is there a way for my organization get into such list? Any criteria/rules?

**Comment by ashkulz** [comment]
@belauzas it should be updating on every run, which country/region where do you feel it's not?

For the second question, it seems to derived from the top users -- see [this function](https://github.com/lauripiispanen/most-active-github-users-counter/blob/54d46dfe291d5f61278ec1291515c45881533490/output/output.go#L247) which is [called during output YML generation](https://github.com/lauripiispanen/most-active-github-users-counter/blob/54d46dfe291d5f61278ec1291515c45881533490/output/output.go#L121).

**Comment by belauzas** [comment]
@ashkulz well, I'm from Lithuania, but now I see (if I'm correct), organizations list depends on what organization is listed on users profile and if it's empty, then code doesn't look into "organizations" section in users profile (left bottom part).

**Comment by ashkulz** [comment]
@belauzas I think for that, you have to set the visibility to "public" -- if I visit [your profile](https://github.com/belauzas), I can't see any organizations listed:

![Screenshot 2021-12-26 at 17-30-38 belauzas - Overview](https://user-images.githubusercontent.com/854352/147407360-7f3aa1e8-11c2-4c6b-a3b7-7f935e945980.png)

Also, congratulations on being the first for your country :tada:

**Comment by belauzas** [comment]
Thank you @ashkulz ! 🚀 And yee... not sure how I missed that organizations are "private"... shame on me 👀

**Comment by ashkulz** [comment]
@belauzas I guess you can close this ticket now? It should show up on the next update now that the visibility has changed -- see #140 for details on that.
