### ISSUE TITLE
List Not Updating

### ISSUE THREAD

**Issue by iamstan13y** [lauripiispanen/most-active-github-users-counter#140]
It's been over a week now _(almost 2 weeks)_ and the list has not yet updated as it should...

**Comment by PulkitSinghDev** [comment]
yes

**Comment by iamstan13y** [comment]
the one managing this project should at least be checking out these issues.

**Comment by lauripiispanen** [comment]
Hi! Yes there are a couple of small updates to be done on the infrastructure side. Will try to do them ASAP.

**Comment by tchiinhemba** [comment]
Any news?

**Comment by jeff-hykin** [comment]
Guys @Kareem-negm @eladioclaudio come on, I'm sure Lauri maintains this thing for free, for everyone, in his spare time. Bumps encase he forgot are fine, but the commit history shows he made changes yesterday. 

Pinging him almost every week about it is just spam. He's welcome to fix it when he feels like fixing it.  If there were any news, I'm sure he'd mention it. And he already stated he'd fix it as soon as possible.

If you really need it fixed, like if you have a tool that depends on it, or you need it for a class project, fix it yourself; its open source.

**Comment by Awilum** [comment]
Last update was on 2021-09-13 
https://commits.top/russia.html - list is not updating

**Comment by Awilum** [comment]
Any updates on this ?

**Comment by jeff-hykin** [comment]
see [committers.top](https://committers.top)

Thanks for picking up the project @ashkulz!

**Comment by ashkulz** [comment]
@iamstan13y list updates have now been [automated via GH Actions](https://github.com/lauripiispanen/github-top/blob/master/.github/workflows/generate.yml), so I guess this isn't applicable any more -- I think you should close this issue :slightly_smiling_face:

**Comment by iamstan13y** [comment]
Thank you for the detailed update.
