### ISSUE TITLE
Bug in (1366x768) screen [Site]

### ISSUE THREAD

**Issue by scarletquasar** [lauripiispanen/most-active-github-users-counter#143]
https://imgur.com/a/uIBFTmZ

Mouse over the project maintainer link is reorganizing the screen in a weird way. Page: (https://commits.top/)

**Comment by ashkulz** [comment]
I think this is a duplicate of lauripiispanen/github-top#212

**Comment by ashkulz** [comment]
@EternalQuasar0206 can you check if this is an issue with [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain)?

**Comment by scarletquasar** [comment]
> @EternalQuasar0206 can you check if this is an issue with [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain)?

Looks like it's solved, can't find the bug anymore in the page
