### ISSUE TITLE
List not up to date for Cameroon

### ISSUE THREAD

**Issue by baimamboukar** [lauripiispanen/most-active-github-users-counter#145]
I went to the page of Cameroon ( https://commits.top/cameroon.html ). And the content is not actually up do date. It is showing the total commits I had 4 months ago

**Comment by ashkulz** [comment]
Please see #140 -- also related to #98 not being implemented.

**Comment by ashkulz** [comment]
@baimamboukar [my fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain) has this actively updated: see https://committers.top/cameroon

**Comment by baimamboukar** [comment]
Clean.... It is working! Up to date

**Comment by baimamboukar** [comment]
Clean.... It is working! Up to date

**Comment by ashkulz** [comment]
@baimamboukar I think it is now up-to-date, you can close this issue.
