### ISSUE TITLE
Blank page on Japan

### ISSUE THREAD

**Issue by craftzdog** [lauripiispanen/most-active-github-users-counter#146]
https://commits.top/japan.html

<img width="739" alt="Screen Shot 2022-01-09 at 18 34 27" src="https://user-images.githubusercontent.com/1332805/148676933-bcb96c2b-46c9-4fba-a879-88e528361569.png">

I can see the lists of other countries.

**Comment by ashkulz** [comment]
@craftzdog this seems to have been fixed, I think you can close this issue.

**Comment by craftzdog** [comment]
Cool, thanks.
