### ISSUE TITLE
Commits not from this year

### ISSUE THREAD

**Issue by donno2048** [lauripiispanen/most-active-github-users-counter#154]
The site only uses this year's commits...

**Comment by lauripiispanen** [comment]
Hi! That is incorrect - it does use full year. At least the ones that are returned by GitHub API.

**Comment by donno2048** [comment]
![image](https://user-images.githubusercontent.com/61805754/156902431-d0495155-ea90-49e0-85ae-5c850f7e7cde.png)
![image](https://user-images.githubusercontent.com/61805754/156902429-254bed17-005e-4053-856e-e37d1a961d24.png)

**Comment by donno2048** [comment]
@lauripiispanen
