### ISSUE TITLE
UK page is empty 

### ISSUE THREAD

**Issue by SmileyJames** [lauripiispanen/most-active-github-users-counter#155]
https://commits.top/uk_public.html
https://commits.top/uk.html

Both these pages don't list anyone for me

**Comment by ArztKlein** [comment]
On my end the UK works fine, but the US lists nothing

**Comment by ashkulz** [comment]
See [this comment](https://github.com/lauripiispanen/most-active-github-users-counter/issues/98#issuecomment-1147468878) for details, I think you should close this issue and add feedback or upvote that issue instead :man_shrugging:

**Comment by SmileyJames** [comment]
closing, working for me now 😄
