### ISSUE TITLE
Ukraine page is empty

### ISSUE THREAD

**Issue by 5HT** [lauripiispanen/most-active-github-users-counter#160]
https://commits.top/ukraine_public.html
https://commits.top/ukraine.html

![зображення](https://user-images.githubusercontent.com/144776/162337240-57a2a596-0588-497d-b902-5ffb8de23ba1.png)

**Comment by ashkulz** [comment]
See [this comment](https://github.com/lauripiispanen/most-active-github-users-counter/issues/98#issuecomment-1147468878) for details, I think you should close this issue and add feedback or upvote that issue instead :man_shrugging:

**Comment by 5HT** [comment]
actually it is working now.
