### ISSUE TITLE
Philippines page is empty

### ISSUE THREAD

**Issue by eun0115** [lauripiispanen/most-active-github-users-counter#163]
[![image](https://user-images.githubusercontent.com/67692232/164573948-b8d65436-c6f1-4ec6-9812-b02d7a6f29da.png)
](https://ibb.co/C7FPrBq)

**Comment by ashkulz** [comment]
See [this comment](https://github.com/lauripiispanen/most-active-github-users-counter/issues/98#issuecomment-1147468878) for details, I think you should close this issue and add feedback or upvote that issue instead :man_shrugging:

**Comment by eun0115** [comment]
well its fixed now on my side, its peobably the best to close this issue
