### ISSUE TITLE
Most Active Github Users JSON API

### ISSUE THREAD

**Issue by 0x15BA88FF** [lauripiispanen/most-active-github-users-counter#169]
This is not a bug but I will like for there to be an API for the website... 
I feel like tweaking the frontend a little bit but I am not very familiar with the Golang

I hope this is not too much to ask for
also if there is an already existing API as such I would like to be informed

😄

**Comment by ashkulz** [comment]
My fork https://committers.top does have a static JSON generated automatically. Please take a look and see if that serves your purpose :+1:
