### ISSUE TITLE
Missing profiles?

### ISSUE THREAD

**Issue by DanielRuf** [lauripiispanen/most-active-github-users-counter#31]
https://commits.top/germany.html

Seems I do not exist there even if I have much more contributions.

**Comment by lauripiispanen** [comment]
Update script runs once a week - looks like you're there now 👍

**Comment by skadyrov** [comment]
Interesting, there are users with the same amount of followers and less contributions in the list, but mine doesn't show up. I saw myself in the list several months ago, but not any more :)
