### ISSUE TITLE
Counter does not refresh count data

### ISSUE THREAD

**Issue by BolajiAyodeji** [lauripiispanen/most-active-github-users-counter#33]
I've stalked the counter for a while now and noticed that it does not refresh the page with the latest contribution count data.
Most times it takes like 1-month max to refresh the counter and then it stops.
Currently, the data rendered on the counts are not valid anymore.

Is there a fix to this, or is this normal?
Or I'm I missing something?

**Comment by lauripiispanen** [comment]
Please elaborate? Counts are updated once a week, and atm they appear to be very close to what is shown on user profile pages, so I’m assuming everything works correctly.

**Comment by BolajiAyodeji** [comment]
Ohh okay!
I thought it was some auto update.
Thanks for the clarification
