### ISSUE TITLE
Sorry, I do not know why my name is not in listed?

### ISSUE THREAD

**Issue by savepong** [lauripiispanen/most-active-github-users-counter#40]
I have 579 contributions and set the location to Bangkok, Thailand.

**Comment by benedekrozemberczki** [comment]
When did you change your location?

**Comment by savepong** [comment]
since last year sir.

**Comment by AnandChowdhary** [comment]
It's because of the number of followers you have. The algorithm fetches the 1,000 most-followed people, and then sorts them by contributions. This is because the GitHub API does not have a way to show users by number of contributions directly.
