### ISSUE TITLE
Ignore cheating users

### ISSUE THREAD

**Issue by albinekb** [lauripiispanen/most-active-github-users-counter#48]
![image](https://user-images.githubusercontent.com/5027156/58329211-4e62ae80-7e34-11e9-9718-b9acb14034b0.png)

Some users have started cheating, anyone got an idea of how to prevent users that are cheating from showing up?

**Comment by lauripiispanen** [comment]
This is related to #37 - i.e. should be possible in the near future. :+1:

**Comment by lauripiispanen** [comment]
#37 is now in production
