### ISSUE TITLE
This ranking rewards popularity over commits, even if they're unrelated. 

### ISSUE THREAD

**Issue by asm128** [lauripiispanen/most-active-github-users-counter#60]
The way of building the ranking is incorrect. Followers should be set to one, and list size could be reduced by account lifetime.

It's also good to note that seniority and code quality is opposite to popularity.

**Comment by lauripiispanen** [comment]
Unfortunately sorting by contributions is not possible in the GitHub API. And yes, this is simply a list sorted by number of contributions, nothing more.

**Comment by asm128** [comment]
Actually, this is first a rank of followers, then sorted by contributions. Plus, you could open an issue for the github api requesting implementation of the obviously missing feature, then close this issue once you get a definitive answer. But it's your public project so it's ok if this is how you handle the issues.
