### ISSUE TITLE
My Account does not shows in List

### ISSUE THREAD

**Issue by NishkarshRaj** [lauripiispanen/most-active-github-users-counter#62]
My [Git account](https://www.github.com/NishkarshRaj) is @NishkarshRaj.
I am from India.
According to the website, I must be in top 100 but my name does not show up.

Please check.

**Comment by NishkarshRaj** [comment]
@Rochet2 Thanks for replying. 👍 
I hope I make my profile better to improve my follower count as well 😄

**Comment by lauripiispanen** [comment]
Thanks @Rochet2! I added an FAQ to clarify this :+1:
