### ISSUE TITLE
My account is not showing up

### ISSUE THREAD

**Issue by LucasLeandro1204** [lauripiispanen/most-active-github-users-counter#67]
I should be listed in this page - https://commits.top/brazil.html
but I'm :(

**Comment by LucasLeandro1204** [comment]
#40

**Comment by LucasLeandro1204** [comment]
Reopening, Just checked and I'm listed in top 1000 most followed too
https://github.com/search?l=&p=78&q=sort%3Afollowers-desc+location%3ABrazil&ref=advsearch&type=Users&utf8=%E2%9C%93

**Comment by lauripiispanen** [comment]
There was a recent change to include only public contributions on the main page of each country. If you have mostly private contributions, you'll probabl find yourself on the subpage with private contributions included.
