### ISSUE TITLE
My account is no longer showing up

### ISSUE THREAD

**Issue by justinvos** [lauripiispanen/most-active-github-users-counter#76]
My account `justinvos` is no longer showing up on the commits.top list even though I have enough followers and commits to be in the teens of the New Zealand list.

**Comment by ar2rsawseen** [comment]
https://github.com/lauripiispanen/most-active-github-users-counter/issues/40

**Comment by lauripiispanen** [comment]
There was a recent change to include only public contributions on the main page of each country. If you have mostly private contributions, you'll probabl find yourself on the subpage with private contributions included.

**Comment by justinvos** [comment]
Ah I see, thanks @lauripiispanen!
