### ISSUE TITLE
Some countries are not updated for at least 2 weeks

### ISSUE THREAD

**Issue by Skobeltsyn** [lauripiispanen/most-active-github-users-counter#77]
Hello, some countries are not updated for at least 2 weeks
e.g.
CA, USA
Canada
Russia
and some more

Is it because of quotas?

**Comment by lauripiispanen** [comment]
Yeah, the graphql API can be a bit flaky sometimes with fetching contribution counts for big countries. I countered this by adding retries and backoff. Should be more stable now. 👍

**Comment by KSkobeltsynStudio** [comment]
Thanks 👍

**Comment by mr-eyes** [comment]
I think this issue has not been resolved yet since **"NY, USA"** & **"CA, USA"** last updated in **"2017-05-16"**.

**Comment by lauripiispanen** [comment]
@mr-eyes that is a different issue - there is no US state-level recurring update set up at the moment.

**Comment by mr-eyes** [comment]
@lauripiispanen I see. Thanks for the clarification.
