### ISSUE TITLE
I'm not in the worlwide ranking, any idea why?

### ISSUE THREAD

**Issue by nicolas-grekas** [lauripiispanen/most-active-github-users-counter#79]
I'm feeling bad for this vanity issue :)
1.1k followers and this:

![image](https://user-images.githubusercontent.com/243674/72008606-7af8f880-3254-11ea-8866-3d372b712423.png)

Yet I'm not in the [worldwide ranking](https://commits.top/worldwide.html), any idea why?

**Comment by ngangavic** [comment]
You need at least 1675 followers to appear on the list

**Comment by nicolas-grekas** [comment]
Ok thanks for the info.
I noticed @fabpot is missing also, while he should listed be at position 2 apparently?
