### ISSUE TITLE
Some users are shown on the wrong country.

### ISSUE THREAD

**Issue by teo-tsirpanis** [lauripiispanen/most-active-github-users-counter#83]
For example, by far [the most prolific GitHub contributor in Greece](https://github.com/dzackgarza) is actually from Athens, Georgia. Same with [the fourth one](https://github.com/bhishanpdl) being from Athens, Ohio.

**Comment by kerolloz** [comment]
same for Egypt
The [first user](https://github.com/rwwagner90) is from Alexandria, Virginia which is in the US.
Not to be confused with Alexandria which is also a city in Egypt.

**Comment by lauripiispanen** [comment]
Yikes! I vote we move to UUIDs for city names to avoid collisions like this in the future. 😆 - Until that happens I added an exclusion list that can be used to filter some locations out. It's a bit tricky to detect them automatically, but if you come across any more, you can send a pull request or add an issue and I'll add them to the list :+1:

**Comment by kerolloz** [comment]
Thank you very much @lauripiispanen. Great work :muscle:!
