### ISSUE TITLE
Hey ! Update required 

### ISSUE THREAD

**Issue by saksham1908** [lauripiispanen/most-active-github-users-counter#85]
Please update the list of Indian contributors -

**Comment by benedekrozemberczki** [comment]
I would recommend you to go over previous issues and have an understanding about the methodology that was used to create the list @saksham1908.

**Comment by priyansh19** [comment]
@lauripiispanen can only update the list right ?

**Comment by priyansh19** [comment]
Please update it

**Comment by lauripiispanen** [comment]
Please check the timestamp on the page. It was updated yesterday and automatically updated every week (apart from last two weeks due to a bug).

**Comment by priyansh19** [comment]
Yeah I saw, It got updated yesterday.
Please can you update it today again 😅

**Comment by lauripiispanen** [comment]
Sorry but no.

**Comment by saksham1908** [comment]
Ohh Okay!

**Comment by priyansh19** [comment]
Hey @lauripiispanen,
Today the list is gonna update right ?
