### ISSUE TITLE
Avatars are broken

### ISSUE THREAD

**Issue by olpeh** [lauripiispanen/most-active-github-users-counter#9]
Hello.
Seems like the avatars are broken. All of the avatars imgs have the same src, `https://avatars3.githubusercontent.com/u/?v=3&s=40`.

Probably the user id is missing.
As an example, my avatar is to be found from `https://avatars2.githubusercontent.com/u/6113341?s=88&v=4`

**Comment by lauripiispanen** [comment]
Yeah, this is fixed in 6875f9a0876d0ad6e17b46cfea930aa57c7ac03f, waiting for next deployment :+1:
