### ISSUE TITLE
Discrepancy in the description of kind of commits for the overall contributions

### ISSUE THREAD

**Issue by Priyanka488** [lauripiispanen/most-active-github-users-counter#91]
The page that displays the total contributions of the user ( public + private ) happens to have the description -
"This list only contains public contributions of each user."

![WhatsApp Image 2020-04-19 at 11 17 12 PM](https://user-images.githubusercontent.com/33698440/79695340-edd23080-8293-11ea-8a90-7e80f22df838.jpeg)

**Comment by midopooler** [comment]
Yeah @Priyanka488 I noticed this description bug and came here to make a PR. But unfortunately didn't got the actual code where its written. Hope OC look upon this issue.

**Comment by midopooler** [comment]
@lauripiispanen thanks for resolving!
