### ISSUE TITLE
Me, myself, I: I've disappeared from your top (France) :)

### ISSUE THREAD

**Issue by bzg** [lauripiispanen/most-active-github-users-counter#93]
Hi there! Just to let you know that I was on the list then disappeared - I think [my stats](https://github.com/bzg/) indicate that there may be something wrong in the 2020-04-20 update?

I hope this is somehow useful.

**Comment by ThisaruGuruge** [comment]
Experiencing the same. #MeToo disappeared from the list.

**Comment by bzg** [comment]
Well, I'm back in the list...

That said, I won't really consider sending the link to ma grand'ma until [this issue](https://github.com/lauripiispanen/most-active-github-users-counter/issues/88) is resolved :)

**Comment by filiptronicek** [comment]
#MeToo from the czech_republic. I am creating an API for this, so it would be helpful if I was included again.

**Comment by GrbavaCigla** [comment]
For some reason on website it says 161 contributions, but I have 238 contributions.

**Comment by lauripiispanen** [comment]
Please check this FAQ - e.g. @GrbavaCigla your total contributions include private contributions, so your actual public contribution count is lower.
