### ISSUE TITLE
Data incorrect(not upto date) some users missing from the list 

### ISSUE THREAD

**Issue by iamfeysal** [lauripiispanen/most-active-github-users-counter#95]
Data incorrect(not up to date) some users missing from the list.
I can't see myself on the list. 
Data on some users are not up to date with Github record.

**Comment by lauripiispanen** [comment]
Please check the FAQ first https://github.com/lauripiispanen/most-active-github-users-counter#user-content-why-am-i-not-on-this-list

**Comment by kroitor** [comment]
@lauripiispanen i have seen my username on the worldwide list a few weeks, ago, but it is not on the list anymore. I pass all the terms from the FAQ – have enough public contributions, have enough followers, don't have anything in my location string (assuming it would land on the worldwide list, not a specific country). It would be awesome if you could take a look into why it is not showing up on the list. Thx!
