### ISSUE TITLE
My name isn't shown in my country results

### ISSUE THREAD

**Issue by OlukaDenis** [lauripiispanen/most-active-github-users-counter#96]
I'm from Uganda but am not among the top list and yet I have several contributions.

**Comment by 3mrdev** [comment]
You should wait till the next round of sync

**Comment by OlukaDenis** [comment]
Okay

**Comment by 3mrdev** [comment]
@OlukaDenis Checkyor name now

**Comment by OlukaDenis** [comment]
Thanks @3mrdev .
I'm now on the list
I will continue to close this issue

**Comment by lauripiispanen** [comment]
Thank you @3mrdev :+1:
