### ISSUE TITLE
update the details on regular basis 

### ISSUE THREAD

**Issue by madilraza** [lauripiispanen/most-active-github-users-counter#98]
update the details on regular basis  and i have seen wrong results for private contributions becuse some one have 1430 cont including last years contr so do it more accurate

**Comment by vinayakkulkarni** [comment]
Does it not work if github api throws 500?

I was able to see myself few weeks ago but I'm unable to see it now

**Comment by ashkulz** [comment]
I've also [started a fork](https://github.com/ashkulz/committers.top#why-is-this-running-on-a-different-domain) which is updated every weekend. @vinayakkulkarni you're [#5 for India](https://committers.top/india#vinayakkulkarni) right now :slightly_smiling_face:

**Comment by ashkulz** [comment]
@madilraza list updates have now been [automated via GH Actions](https://github.com/lauripiispanen/github-top/blob/master/.github/workflows/generate.yml), so I guess this isn't applicable any more -- I think you should close this issue :slightly_smiling_face:

**Comment by ashkulz** [comment]
Although the list updates have been automated via GH Actions, there is no error checking present. This causes the data to be deleted randomly for different regions, and which come back on the next run.

The solution is to not proceed if the CLI returns an error code, leaving the old stale data. In [my fork](https://github.com/ashkulz/committers.top), I specifically detect this situation and re-run it till it's successful.
