### ISSUE TITLE
how to get that list with REST API ?

### ISSUE THREAD

**Issue by Dastnbek** [lauripiispanen/most-active-github-users-counter#99]
I'm new developer. I want to make such rank for my country

**Comment by filiptronicek** [comment]
You can use my API! Just made it: [filiptronicek/commits-top-api](https://github.com/filiptronicek/commits-top-api)
Just make an API request to https://commiters.now.sh/rank/country @Dastnbek

**Comment by Dastnbek** [comment]
I'm only getting list of czech_republic @filiptronicek

**Comment by filiptronicek** [comment]
That shouldn't happen, will change it ASAP

**Comment by filiptronicek** [comment]
Should work now @Dastnbek!

**Comment by Dastnbek** [comment]
Yep. It is working and sorting according to public contributions of each user. 
@filiptronicek
